server:
  port: 8098

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.com.cargo.upload_car.entity
  config-location: classpath:mybatis.xml
# 数据库访问配置
# 主数据源，默认的

spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
